[package]
name = "flux-syntax"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
logos.workspace = true
rowan.workspace = true
flux-errors = { path = "../flux-errors" }

[dev-dependencies]
insta.workspace = true
